# Generated by Django 5.1.2 on 2024-11-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("signin_required", models.BooleanField(default=False)),
                ("route_id", models.CharField(max_length=6)),
                ("in_session", models.BooleanField(default=True)),
                ("students", models.JSONField(default=list)),
                ("student_count", models.IntegerField(default=0)),
            ],
        ),
    ]
