# Generated by Django 5.1.2 on 2024-11-28 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_class_classsession"),
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creation_date"
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.user",
            ),
            preserve_default=False,
        ),
    ]
