# Generated by Django 5.1.2 on 2024-11-29 05:25

import util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_classsession_creation_classsession_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classsession",
            name="route_id",
            field=models.CharField(default=util.generate_route_id, max_length=6),
        ),
    ]
