# Generated by Django 5.1.2 on 2024-10-14 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="date_taken",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 14, 15, 35, 43, 180273, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date taken",
            ),
            preserve_default=False,
        ),
    ]
