# Generated by Django 5.1.2 on 2024-10-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_id", models.CharField(max_length=6)),
                ("opening", models.DateTimeField()),
                ("closing", models.DateTimeField()),
                ("code", models.CharField(max_length=6)),
                ("count", models.IntegerField(default=0)),
                ("attendees", models.JSONField(default=list)),
            ],
        ),
    ]
