# Generated by Django 5.1.2 on 2024-10-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("route_id", models.CharField(max_length=6)),
                ("sessions", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening", models.DateTimeField()),
                ("closing", models.DateTimeField()),
                ("count", models.IntegerField(default=0)),
                (
                    "attendance_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.attendancecode",
                    ),
                ),
            ],
        ),
    ]
