# Generated by Django 5.1.2 on 2024-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_attendance_date_taken"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attendance",
            new_name="AttendanceSession",
        ),
        migrations.AddField(
            model_name="attendancecode",
            name="route_id",
            field=models.CharField(default="asdfgh", max_length=6),
            preserve_default=False,
        ),
    ]
