# Generated by Django 5.1.2 on 2024-10-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_attendance_attendancesession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecode",
            name="session_pk",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
