# Generated by Django 5.1.2 on 2024-10-14 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_attendancecode_session_pk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancecode",
            name="session_pk",
        ),
        migrations.AddField(
            model_name="attendancecode",
            name="sessions",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendancecode",
            name="closing",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="attendancecode",
            name="opening",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="date_taken",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 14, 23, 9, 29, 448103, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
