# Generated by Django 5.1.2 on 2024-10-14 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_attendancecode_session_pk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="date_taken",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
