# Generated by Django 5.1.2 on 2024-10-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_attendancesession_date_taken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancecode",
            name="sessions",
            field=models.JSONField(default=list),
        ),
    ]
