# Generated by Django 5.1.2 on 2024-11-30 05:53

import django.db.models.deletion
import django.utils.timezone
import util
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "route_id",
                    models.CharField(default=util.generate_route_id, max_length=6),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("answers", models.JSONField(default=list)),
                (
                    "creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation_date"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.classsession",
                    ),
                ),
            ],
        ),
    ]
